# Generated by Django 2.0 on 2017-12-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='api',
            name='final_date',
            field=models.DateTimeField(),
        ),
    ]
